[general]
library_name = "libcudss"
output_file_path = "../src/libcudss.jl"
prologue_file_path = "./libcudss_prologue.jl"

output_ignorelist = [
    "CUDSS_ALLOCATOR_NAME_LEN",
    "CUDSS_VERSION",
    "CUDSS_VERSION_MAJOR",
    "CUDSS_VERSION_MINOR",
    "CUDSS_VERSION_PATCH"
]

[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true

[api]
checked_rettypes = [ "cudssStatus_t" ]

[api.cudssGetVersion]
needs_context = false

[api.cudssGetProperty]
needs_context = false

