name: Aqua
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Aqua.jl
        run: julia --color=yes -e 'using Pkg; Pkg.add("Aqua"); Pkg.add("CUDA"); Pkg.develop(path=".");
                                   using Aqua, CUDA.CUSPARSE, CUDSS; Aqua.test_all(CUDSS, piracies=false, ambiguities=false);
                                   Aqua.test_ambiguities(CUDSS); Aqua.test_piracies(CUDSS; treat_as_own=[CuSparseMatrixCSR])'
